### ISSUE TITLE
Needs update to work with Forge 14.21.1.2387

### ISSUE THREAD

**Issue by Zarepheth** [Nuchaz/BiblioCraft#475]
Using the recommended Forge for MC 1.12, BiblioCraft seems to be crashing the game at startup. I suspect this is due to Forge's recent change to its Mod registration system.

```
Minecraft:	1.12
Forge:		14.21.1.2387
BiblioCraft:	2.4.2
```

```
[20:07:14] [main/INFO] [FML]: Holder lookups applied
[20:07:14] [main/INFO] [FML]: OBJLoader: Domain bibliocraft has been added.
[20:07:14] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.ModelRegistryEvent@329a4133:
java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/RegistryDelegate
	at net.minecraft.client.renderer.block.model.ModelBakery.registerItemVariants(ModelBakery.java:1081) ~[cfz.class:?]
	at net.minecraftforge.client.model.ModelLoader.setCustomModelResourceLocation(ModelLoader.java:1126) ~[ModelLoader.class:?]
	at jds.bibliocraft.ClientProxy.registerRenderers(ClientProxy.java:253) ~[ClientProxy.class:?]
	at jds.bibliocraft.BiblioCraft$RegisterTheThings.registerModels(BiblioCraft.java:196) ~[BiblioCraft$RegisterTheThings.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_5_RegisterTheThings_registerModels_ModelRegistryEvent.invoke(.dynamic) 
	...
```

[Log File on paste.ee](https://paste.ee/p/FpMaU)

**Comment by Zarepheth** [comment]
The problem might be with Optifine rather than your mod. It looks like Optifine is intercepting model registration.
Suspect frame in stack trace:
```
at ...
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_5_RegisterTheThings_registerModels_ModelRegistryEvent.invoke(.dynamic)
at ...
```

**Comment by Nuchaz** [comment]
this is an optifine issue. Not sure if it has been fixed yet, but forge had rewritten the whole registry system so optifine will have to make changes on their end to be compatible.
